// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WorkerRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkerRequest) Reset()         { *m = WorkerRequest{} }
func (m *WorkerRequest) String() string { return proto.CompactTextString(m) }
func (*WorkerRequest) ProtoMessage()    {}
func (*WorkerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *WorkerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerRequest.Unmarshal(m, b)
}
func (m *WorkerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerRequest.Marshal(b, m, deterministic)
}
func (m *WorkerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerRequest.Merge(m, src)
}
func (m *WorkerRequest) XXX_Size() int {
	return xxx_messageInfo_WorkerRequest.Size(m)
}
func (m *WorkerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerRequest proto.InternalMessageInfo

func (m *WorkerRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *WorkerRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type RequestInfo struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestInfo) Reset()         { *m = RequestInfo{} }
func (m *RequestInfo) String() string { return proto.CompactTextString(m) }
func (*RequestInfo) ProtoMessage()    {}
func (*RequestInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *RequestInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestInfo.Unmarshal(m, b)
}
func (m *RequestInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestInfo.Marshal(b, m, deterministic)
}
func (m *RequestInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestInfo.Merge(m, src)
}
func (m *RequestInfo) XXX_Size() int {
	return xxx_messageInfo_RequestInfo.Size(m)
}
func (m *RequestInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RequestInfo proto.InternalMessageInfo

func (m *RequestInfo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *RequestInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type WorkerResult struct {
	Payload              []*any.Any     `protobuf:"bytes,1,rep,name=payload,proto3" json:"payload,omitempty"`
	Requests             []*RequestInfo `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *WorkerResult) Reset()         { *m = WorkerResult{} }
func (m *WorkerResult) String() string { return proto.CompactTextString(m) }
func (*WorkerResult) ProtoMessage()    {}
func (*WorkerResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *WorkerResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkerResult.Unmarshal(m, b)
}
func (m *WorkerResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkerResult.Marshal(b, m, deterministic)
}
func (m *WorkerResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerResult.Merge(m, src)
}
func (m *WorkerResult) XXX_Size() int {
	return xxx_messageInfo_WorkerResult.Size(m)
}
func (m *WorkerResult) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerResult.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerResult proto.InternalMessageInfo

func (m *WorkerResult) GetPayload() []*any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *WorkerResult) GetRequests() []*RequestInfo {
	if m != nil {
		return m.Requests
	}
	return nil
}

type PersonBriefPayload struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonBriefPayload) Reset()         { *m = PersonBriefPayload{} }
func (m *PersonBriefPayload) String() string { return proto.CompactTextString(m) }
func (*PersonBriefPayload) ProtoMessage()    {}
func (*PersonBriefPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *PersonBriefPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonBriefPayload.Unmarshal(m, b)
}
func (m *PersonBriefPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonBriefPayload.Marshal(b, m, deterministic)
}
func (m *PersonBriefPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonBriefPayload.Merge(m, src)
}
func (m *PersonBriefPayload) XXX_Size() int {
	return xxx_messageInfo_PersonBriefPayload.Size(m)
}
func (m *PersonBriefPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonBriefPayload.DiscardUnknown(m)
}

var xxx_messageInfo_PersonBriefPayload proto.InternalMessageInfo

func (m *PersonBriefPayload) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *PersonBriefPayload) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PersonPayload struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Region               string   `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Age                  int32    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Edu                  string   `protobuf:"bytes,5,opt,name=edu,proto3" json:"edu,omitempty"`
	MaritalStatus        string   `protobuf:"bytes,6,opt,name=maritalStatus,proto3" json:"maritalStatus,omitempty"`
	Height               int32    `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	Weight               int32    `protobuf:"varint,8,opt,name=weight,proto3" json:"weight,omitempty"`
	Salary               []int32  `protobuf:"varint,9,rep,packed,name=salary,proto3" json:"salary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonPayload) Reset()         { *m = PersonPayload{} }
func (m *PersonPayload) String() string { return proto.CompactTextString(m) }
func (*PersonPayload) ProtoMessage()    {}
func (*PersonPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{4}
}

func (m *PersonPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonPayload.Unmarshal(m, b)
}
func (m *PersonPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonPayload.Marshal(b, m, deterministic)
}
func (m *PersonPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonPayload.Merge(m, src)
}
func (m *PersonPayload) XXX_Size() int {
	return xxx_messageInfo_PersonPayload.Size(m)
}
func (m *PersonPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonPayload.DiscardUnknown(m)
}

var xxx_messageInfo_PersonPayload proto.InternalMessageInfo

func (m *PersonPayload) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PersonPayload) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PersonPayload) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *PersonPayload) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *PersonPayload) GetEdu() string {
	if m != nil {
		return m.Edu
	}
	return ""
}

func (m *PersonPayload) GetMaritalStatus() string {
	if m != nil {
		return m.MaritalStatus
	}
	return ""
}

func (m *PersonPayload) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *PersonPayload) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *PersonPayload) GetSalary() []int32 {
	if m != nil {
		return m.Salary
	}
	return nil
}

func init() {
	proto.RegisterType((*WorkerRequest)(nil), "rpc.WorkerRequest")
	proto.RegisterType((*RequestInfo)(nil), "rpc.RequestInfo")
	proto.RegisterType((*WorkerResult)(nil), "rpc.WorkerResult")
	proto.RegisterType((*PersonBriefPayload)(nil), "rpc.PersonBriefPayload")
	proto.RegisterType((*PersonPayload)(nil), "rpc.PersonPayload")
}

func init() {
	proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1)
}

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x49, 0xd2, 0xbf, 0x57, 0x8a, 0x8a, 0x85, 0x90, 0xe9, 0x14, 0x45, 0x0c, 0x1d, 0x50,
	0x2a, 0xb5, 0x62, 0x61, 0x2b, 0x4c, 0x6c, 0x55, 0x18, 0x98, 0xdd, 0xc6, 0x4d, 0x23, 0xdc, 0x38,
	0x9c, 0x1d, 0x55, 0xf9, 0xb0, 0x7c, 0x17, 0x64, 0x3b, 0x29, 0x54, 0x62, 0x60, 0xbb, 0xfb, 0xf9,
	0x9e, 0xdf, 0x4b, 0xce, 0x30, 0xc4, 0x72, 0x1b, 0x97, 0x28, 0xb5, 0x24, 0x01, 0x96, 0xdb, 0xe9,
	0x5d, 0x26, 0x65, 0x26, 0xf8, 0xdc, 0xa2, 0x4d, 0xb5, 0x9b, 0xb3, 0xa2, 0x76, 0xe7, 0xd1, 0x23,
	0x8c, 0xdf, 0x25, 0x7e, 0x70, 0x4c, 0xf8, 0x67, 0xc5, 0x95, 0x26, 0x13, 0x08, 0x2a, 0x14, 0xd4,
	0x0b, 0xbd, 0xd9, 0x30, 0x31, 0x25, 0x21, 0xd0, 0xd1, 0x75, 0xc9, 0xa9, 0x6f, 0x91, 0xad, 0xa3,
	0x25, 0x8c, 0x1a, 0xc1, 0x6b, 0xb1, 0x93, 0xff, 0x14, 0x09, 0xb8, 0x6c, 0xbd, 0x54, 0x25, 0x34,
	0x89, 0xa1, 0x5f, 0xb2, 0x5a, 0x48, 0x96, 0x52, 0x2f, 0x0c, 0x66, 0xa3, 0xc5, 0x4d, 0xec, 0x82,
	0xc6, 0x6d, 0xd0, 0x78, 0x55, 0xd4, 0x49, 0x3b, 0x44, 0x1e, 0x60, 0x80, 0xce, 0x54, 0x51, 0xdf,
	0x0a, 0x26, 0xb1, 0xf9, 0xd2, 0x5f, 0x49, 0x92, 0xd3, 0x44, 0xf4, 0x04, 0x64, 0xcd, 0x51, 0xc9,
	0xe2, 0x19, 0x73, 0xbe, 0x5b, 0x37, 0x77, 0xfc, 0x99, 0xb4, 0x60, 0x87, 0x53, 0x52, 0x53, 0x47,
	0x5f, 0x1e, 0x8c, 0x9d, 0xb8, 0xd5, 0xb5, 0x53, 0xde, 0xcf, 0x14, 0xb9, 0x02, 0x3f, 0x4f, 0x1b,
	0x9d, 0x9f, 0xa7, 0xe4, 0x16, 0x7a, 0xc8, 0xb3, 0x5c, 0x16, 0x34, 0xb0, 0xac, 0xe9, 0x8c, 0x27,
	0xcb, 0x38, 0xed, 0x84, 0xde, 0xac, 0x9b, 0x98, 0xd2, 0x10, 0x9e, 0x56, 0xb4, 0xeb, 0x52, 0xf0,
	0xb4, 0x22, 0xf7, 0x30, 0x3e, 0x30, 0xcc, 0x35, 0x13, 0x6f, 0x9a, 0xe9, 0x4a, 0xd1, 0x9e, 0x3d,
	0x3b, 0x87, 0xc6, 0x61, 0xcf, 0xf3, 0x6c, 0xaf, 0x69, 0xdf, 0x5e, 0xd6, 0x74, 0x86, 0x1f, 0x1d,
	0x1f, 0x38, 0x7e, 0x3c, 0x71, 0xc5, 0x04, 0xc3, 0x9a, 0x0e, 0xc3, 0xc0, 0x70, 0xd7, 0x2d, 0x56,
	0x30, 0x7a, 0x41, 0x76, 0x14, 0x1c, 0xcd, 0x42, 0xc8, 0x02, 0xfa, 0x6b, 0x94, 0x5b, 0xae, 0x14,
	0x21, 0xf6, 0x8f, 0x9e, 0x3d, 0x89, 0xe9, 0xf5, 0x19, 0x33, 0xab, 0x8b, 0x2e, 0x36, 0x3d, 0xbb,
	0xa3, 0xe5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x79, 0x9d, 0x93, 0x6c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CrawlerWorkClient is the client API for CrawlerWork service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CrawlerWorkClient interface {
	// Sends a greeting
	Process(ctx context.Context, in *WorkerRequest, opts ...grpc.CallOption) (*WorkerResult, error)
}

type crawlerWorkClient struct {
	cc grpc.ClientConnInterface
}

func NewCrawlerWorkClient(cc grpc.ClientConnInterface) CrawlerWorkClient {
	return &crawlerWorkClient{cc}
}

func (c *crawlerWorkClient) Process(ctx context.Context, in *WorkerRequest, opts ...grpc.CallOption) (*WorkerResult, error) {
	out := new(WorkerResult)
	err := c.cc.Invoke(ctx, "/rpc.CrawlerWork/Process", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrawlerWorkServer is the server API for CrawlerWork service.
type CrawlerWorkServer interface {
	// Sends a greeting
	Process(context.Context, *WorkerRequest) (*WorkerResult, error)
}

// UnimplementedCrawlerWorkServer can be embedded to have forward compatible implementations.
type UnimplementedCrawlerWorkServer struct {
}

func (*UnimplementedCrawlerWorkServer) Process(ctx context.Context, req *WorkerRequest) (*WorkerResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}

func RegisterCrawlerWorkServer(s *grpc.Server, srv CrawlerWorkServer) {
	s.RegisterService(&_CrawlerWork_serviceDesc, srv)
}

func _CrawlerWork_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerWorkServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.CrawlerWork/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerWorkServer).Process(ctx, req.(*WorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CrawlerWork_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.CrawlerWork",
	HandlerType: (*CrawlerWorkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _CrawlerWork_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
